language: node_js
node_js:
  - "6.2.2"
  - "5.12.0"
  - "4.4.7"
  - "iojs"
  - "0.12"
sudo: false
env:
  matrix:
    - WEBPACK_VERSION=1.13.1 WEBPACK_DEV_SERVER_VERSION=1.7.0
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm rm webpack webpack-dev-server
  - npm install webpack@$WEBPACK_VERSION webpack-dev-server@$WEBPACK_DEV_SERVER_VERSION
script:
  - "node_modules/.bin/testem ci -l firefox"
